# ARCHIVO: docker-compose.yml  
#(DEFINIMOS  LA CONFIGURACION PARA EJECUTAR VARIOS CONTENEDORES A LA VEZ)

services:
  # Cada servicio corresponde a un contenedor
  gimnasio-app:
    build: .            #IMPORTANTISIMOOOO: Aquí le estamos diciendo a docker-compose.yml donde está el archivo Dockerfile(en este caso está en este mismo directorio) 
                        #Si no usaramos Dockerfile, en lugar de build: . usariamos una imagen (COMO LO ESTAMOS HACIENDO ABAJO EN EL CONTEneDOR MARIADB)
    container_name: app-spring
    restart: unless-stopped
    depends_on:
      - postgresql
    ports:
      - "8081:8080"  # Mapea el puerto 8081 al 8080 interno
    # Cargamos las variables del archivo .env
    #IMPORTANTE: Nuestro .env no está haciendo nada ya que en enviroment estamos sobrescribiendo esas variables
    env_file:
      - .env
    environment:   #MUY IMPORTANTE: al hacer esto hacemos que tome estas variables y no preste atención a las del .env ya que enviroment tiene mayor prioridad que .env
      # Mapea variables al formato que Spring espera
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/Gimnasio   
      #la URL de la bbdd no funcionaria si pusieramos jdbc:mariadb://localhost:3306/Gimnasio 
      # YA QUE COMO LA BBDD ESTA EN OTRO CONTENEDOR NO PODRIA ACCEDER

      SPRING_DATASOURCE_USERNAME: UsuarioAdmin
      SPRING_DATASOURCE_PASSWORD: admin123

      #open ai
      API_KEY: ${API_KEY}

      #cloudinary
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUD_API_KEY: ${CLOUD_API_KEY}
      CLOUD_API_SECRET: ${CLOUD_API_SECRET}

  # MariaDB 
  postgresql:
    image: postgres:15  # Imagen de PostgreSQL
    container_name: app-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: Gimnasio
      POSTGRES_USER: UsuarioAdmin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"  # Puerto diferente al de MariaDB (3306)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # phpmyadmin NO funciona con PostgreSQL, necesitas pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: app-pgadmin
    restart: unless-stopped
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"  # Mismo puerto que usabas para phpmyadmin

volumes:
  postgres_data: